# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trussle Product Development
email: team@trussle.com
description: > # this means to ignore newlines until "baseurl:"
  Trussle Product Development build stuff for Trussle, a new kind of mortgage adviser.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://trussle.github.io" # the base hostname & protocol for your site
twitter_username: hellotrussle
github_username:  trussle

# Build settings
markdown: kramdown
